### ISSUE TITLE
Timeout waiting for status response with Eufy X8 Hybrid

### ISSUE THREAD

**Issue by maulai** [hov3rcraft/homebridge-eufy-robovac#10]
Hi, thank you for you work.
Unfortunately this doesn't seem to work with my vacuum. Whenever I try to turn the device on, the following ist printed and nothing happens:
`Error! Timeout waiting for status response from device id: bf268******
Disconnected from device.
Setting Running to true successful.`

I had the plugin configured both with static IP and without and did multiple restarts and even a reinstall of the plugin, but the output stayed the same.

Complete logs with debug mode turned on:
```
Connected to device!
Received data from device: 
-- Status Start --
- Default Property (ignore): true
- Running: false
- Work Mode: auto
- Work Status: Charging
- Go Home: false
- Clean Speed: Standard
- Find Robot: false
- Battery Level: 100
- Error Code: 0
-- Status End --
updateCharacteristics for Vacuum Cleaner
updating Running for Vacuum Cleaner to false
updating Battery Level for Vacuum Cleaner to 100
updating Work Status for Vacuum Cleaner to Charging
updateCharacteristics for Vacuum Cleaner complete - updated 3 characteristics.
Received data from device: 
-- Status Start --
- Default Property (ignore): true
- Running: false
- Work Mode: auto
- Work Status: Charging
- Go Home: false
- Clean Speed: Standard
- Find Robot: false
- Battery Level: 100
- Error Code: 0
-- Status End --
updateCharacteristics for Vacuum Cleaner
updating Running for Vacuum Cleaner to false
updating Battery Level for Vacuum Cleaner to 100
updating Work Status for Vacuum Cleaner to Charging
updateCharacteristics for Vacuum Cleaner complete - updated 3 characteristics.
Status update retrieved.
getRunning for Vacuum Cleaner
Status request within max status update age
getLowBattery for Vacuum Cleaner
Status request within max status update age
getBatteryLevel for Vacuum Cleaner
Status request within max status update age
getCharging for Vacuum Cleaner
Status request within max status update age
getRunning for Vacuum Cleaner
Status request within max status update age
getLowBattery for Vacuum Cleaner
Status request within max status update age
getBatteryLevel for Vacuum Cleaner
Status request within max status update age
getCharging for Vacuum Cleaner
Status request within max status update age
setRunning for Vacuum Cleaner set to true
Setting Running to true ...
getRunning for Vacuum Cleaner
Status request within max status update age
getRunning for Vacuum Cleaner
Status request within max status update age
getLowBattery for Vacuum Cleaner
Status request within max status update age
getBatteryLevel for Vacuum Cleaner
Status request within max status update age
getCharging for Vacuum Cleaner
Status request within max status update age
Error! Timeout waiting for status response from device id: bf268******
Disconnected from device.
Setting Running to true successful.
```

**Comment by hov3rcraft** [comment]
Hi! Is the running/not running status correctly shown in the Home app when you start the vacuum cleaner manually using the remote or in the Eufy app?

**Comment by huskey404** [comment]
also having this problem with my L50 SES
I have device id, local key, and ip plugged into the config (I have tried running it without it the ip)

```
setRunning for Vacuum Cleaner set to true
Setting Running to true ...
Error! Timeout waiting for status response from device id: eb117...
Disconnected from device.
An error occurred! (during SET of Running to true ):  Error: Timeout waiting for status response from device id: eb117...
    at /var/lib/homebridge/node_modules/@hov3rcraft/homebridge-eufy-robovac/node_modules/tuyapi/index.js:460:15
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/@hov3rcraft/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
```

seems to not be able to gather any data whatsoever
```
Received dps refresh data from device: 
-- Status Start --
-- Status End --
updateCharacteristics for Vacuum Cleaner
updateCharacteristics for Vacuum Cleaner complete - updated 0 characteristics.
```
